#!/usr/bin/env python3

import torch
from kospeech.models import DeepSpeech2


if __name__ == '__main__' :
    cuda = torch.cuda.is_available()
    device = torch.device('cuda' if cuda else 'cpu')

    print(device)